management:
  security:
    enabled: false
spring:
  zipkin:
    base-url: http://192.168.99.100:9411/
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

