server:
  port: 8091
spring:
  data:
    mongodb:
      host: vm-docker
  profiles:
    active: message2
      
---
spring:
    profiles: message1
catalog:
  message: Salut, toi!
---
spring:
    profiles: message2
catalog:
  message: Salut, toi! Bis!
